export const DRINKS_FETCH = "DRINKS_FETCH";
export const DRINKS_FETCH_SUCCESS = "DRINKS_FETCH_SUCCESS";
export const DRINKS_FETCH_FAIL = "DRINKS_FETCH_FAIL";
export const DRINKS_FILTER_CHANGE = "DRINKS_FILTER_CHANGE";
export const DRINKS_SELECT = "DRINKS_SELECT";
